CREATE TABLE `fx_entry_pattern` (
  `code` varchar(16) NOT NULL COMMENT 'エントリーパターンコード',
  `trade_type` char(1) NOT NULL COMMENT '売買フラグ(L:買い/S:売り)',
  `entry_key` char(2) NOT NULL COMMENT 'エントリーKEY(RV|FR|F3|UD|ZZ)',
  `entry_type` varchar(32) NOT NULL COMMENT 'エントリー種別(F3_XX|FR_XX|RV_XX|UD_XXなど)',
  `fibonacci_type` char(2) NOT NULL COMMENT 'エントリーF種別(RV|RR|UP|DW)',
  `fibonacci_bar` varchar(8) NOT NULL COMMENT 'エントリーFバー(15m|v15m|5m|v5mなど)',
  `fibonacci_bar_r` varchar(8) NOT NULL COMMENT '4H200逆行-エントリーFバー(15m|v15m|5m|v5mなど)',
  `is_reverse` bit(1) NOT NULL DEFAULT b'0' COMMENT '逆張りフラグ',
  `is_elliott3` bit(1) NOT NULL DEFAULT b'0' COMMENT 'E3フラグ',
  `is_perfect_order` bit(1) NOT NULL DEFAULT b'0' COMMENT 'PerfectOrderフラグ',
  `position1` varchar(8) NOT NULL COMMENT 'ポジション1利確',
  `position1_stop_loss` varchar(16) NULL COMMENT 'ポジション1_StopLoss',
  `position2` varchar(16) NULL COMMENT 'ポジション2利確',
  `position2_stop_loss` varchar(16) NULL COMMENT 'ポジション2_StopLoss',
  `position3` varchar(16) NULL COMMENT 'ポジション3_利確',
  `position3_stop_loss` varchar(16) NULL COMMENT 'ポジション3_StopLoss',
  `entry_memo` text DEFAULT NULL COMMENT 'メモ',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '削除フラグ',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'レコード作成日時',
  `created_by` varchar(128) NOT NULL COMMENT 'レコード作成者情報',
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'レコード更新日時',
  `updated_by` varchar(128) NOT NULL COMMENT 'レコード更新者情報',
  PRIMARY KEY (`code`, `trade_type`),
  KEY `fx_entry_pattern_idx1` (`entry_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='エントリーパターン';
