CREATE TABLE `fx_verification_entry` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `trade_version` varchar(16) NOT NULL COMMENT 'tradeVersion.V1|V2,,,',
  `symbol` varchar(6) NOT NULL COMMENT '通貨ペア',
  `trade_type` char(1) NOT NULL COMMENT '売買フラグ(L:買い/S:売り)',
  `contract_at` datetime NOT NULL COMMENT '約定日時',
  `entry_type` char(2) NOT NULL COMMENT 'エントリー種別(F3|FR|F7|UP|DW)',
  `fibonacci_type` char(2) NOT NULL COMMENT 'エントリーF種別(RV|RR|UP|DW)',
  `fibonacci_bar` varchar(16) NOT NULL COMMENT 'エントリーFバー(15m|v15m|5m|v5mなど)',
  `contract_price` decimal(10,5) NOT NULL COMMENT '約定値',
  `loss_price` decimal(10,5) NOT NULL COMMENT '逆指値',
  `risk_amount` int(11) NOT NULL COMMENT 'リスク金額',
  `position_ratio` int(11) NOT NULL COMMENT 'lot1 ratio',
  `price_jpy` decimal(10,3) NOT NULL COMMENT 'UsdJpy始値',
  `lot` decimal(10,5) NOT NULL COMMENT 'LOT',
  `settlement_amount` int(11) NOT NULL COMMENT '決済額',
  `loss_pips` int(11) NOT NULL COMMENT '損失pips',
  `settlement_ratio` decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT '決済損益比率(settlement_pips/loss_pips)',
  `comment` text DEFAULT NULL COMMENT 'エントリーコメント',
  PRIMARY KEY (`id`),
  UNIQUE KEY (`trade_version`, `symbol`, `trade_type`,`contract_at`),
  KEY (`entry_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='FXトレードエントリー情報';
